name: Build and Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build-ios:
    name: Build IPA
    runs-on: macos-15
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run ipabuild.sh
        run: |
          chmod +x ipabuild.sh
          ./ipabuild.sh ios
          
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sora-IPA
          path: build/Sora.ipa
          compression-level: 0

  build-tvos:
    name: Build tvOS
    runs-on: macos-15
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run ipabuild.sh for tvOS
        run: |
          chmod +x ipabuild.sh
          ./ipabuild.sh tvos
          
      - name: Upload tvOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sora-tvOS
          path: build/Sora-tvOS.ipa
          compression-level: 0
